import type {
  CoreVisualMeshId,
  ImpactVfxId,
  SpellAlignmentId,
  SpellShaderId,
  SpellShaderSelection,
  SpellStatusEffectId,
  TravelVfxId,
} from "@/game/spells/modules/spellIds";

export type SpellPalette = {
  primary: string;
  secondary: string;
  accent: string;
  dark: string;
};

export type AlignmentDefinition = {
  id: SpellAlignmentId;
  label: string;
  primaryVisuals: string;
  mechanic: string;
  statusEffect: SpellStatusEffectId;
  palette: SpellPalette;
  defaultCoreMesh: CoreVisualMeshId;
  defaultTravel: TravelVfxId[];
  defaultImpact: ImpactVfxId[];
  defaultShaders: SpellShaderSelection;
  allowedShaders: SpellShaderId[];
};

export const alignmentCatalog: Record<SpellAlignmentId, AlignmentDefinition> = {
  fire: {
    id: "fire",
    label: "Fire",
    primaryVisuals: "orange, red, yellow, high glow, smoke, embers",
    mechanic: "high initial damage, fast pressure",
    statusEffect: "burn",
    palette: { primary: "#ff6a2a", secondary: "#ff2f18", accent: "#ffd66b", dark: "#3b0f08" },
    defaultCoreMesh: "sphere",
    defaultTravel: ["particle_trail", "core_glow"],
    defaultImpact: ["burst_explosion", "flash", "lingering_cloud"],
    defaultShaders: {
      core: "flame_core",
      trail: "ember_trail",
      impact: "blast_flash",
      decal: "molten_crack",
      aura: "ember_shell",
    },
    allowedShaders: [
      "flame_core",
      "ember_shell",
      "heat_haze",
      "molten_crack",
      "ember_trail",
      "smoke_fire_trail",
      "comet_flame_trail",
      "blast_flash",
      "shockwave_ring",
      "smoke_plume",
      "sparks_burst",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
  water_ice: {
    id: "water_ice",
    label: "Water / Ice",
    primaryVisuals: "blue, cyan, white, translucency, mist, fractured frost",
    mechanic: "piercing pressure, splashes, area control",
    statusEffect: "chill",
    palette: { primary: "#8ae9ff", secondary: "#2f9fff", accent: "#ffffff", dark: "#0a3158" },
    defaultCoreMesh: "jagged_crystal",
    defaultTravel: ["particle_trail", "core_glow"],
    defaultImpact: ["burst_explosion", "ground_decal", "lingering_cloud"],
    defaultShaders: {
      core: "frost_crystal",
      trail: "mist_shell",
      impact: "ice_glass",
      decal: "water_ripple",
      aura: "mist_shell",
    },
    allowedShaders: [
      "frost_crystal",
      "ice_glass",
      "water_ripple",
      "mist_shell",
      "shockwave_ring",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
  lightning: {
    id: "lightning",
    label: "Lightning",
    primaryVisuals: "yellow, purple, bright white, jagged arcs",
    mechanic: "instant travel, erratic chains, interruption",
    statusEffect: "stun",
    palette: { primary: "#fff36a", secondary: "#b96cff", accent: "#ffffff", dark: "#261246" },
    defaultCoreMesh: "none",
    defaultTravel: ["core_glow", "swirling_vortex"],
    defaultImpact: ["flash", "burst_explosion"],
    defaultShaders: {
      core: "plasma_arc",
      trail: "chain_bolt",
      impact: "electric_noise",
      decal: "storm_core",
      aura: "storm_core",
    },
    allowedShaders: [
      "plasma_arc",
      "storm_core",
      "chain_bolt",
      "electric_noise",
      "blast_flash",
      "blinding_flash",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
  earth: {
    id: "earth",
    label: "Earth",
    primaryVisuals: "brown, green, dust, debris, stone geometry",
    mechanic: "heavy impact, physical disruption",
    statusEffect: "stagger",
    palette: { primary: "#b4834b", secondary: "#5f7f3d", accent: "#e0c08a", dark: "#2f2117" },
    defaultCoreMesh: "boulder",
    defaultTravel: ["particle_trail"],
    defaultImpact: ["burst_explosion", "lingering_cloud", "ground_decal"],
    defaultShaders: {
      core: "stone_rune",
      trail: "dust_cloud",
      impact: "sand_burst",
      decal: "stone_rune",
      aura: "moss_glow",
    },
    allowedShaders: [
      "dust_cloud",
      "stone_rune",
      "moss_glow",
      "sand_burst",
      "toxic_bubble",
      "acid_sizzle",
      "spore_cloud",
      "thorn_glow",
      "shockwave_ring",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
  dark: {
    id: "dark",
    label: "Dark",
    primaryVisuals: "black, deep purple, void swirls, smoky tendrils",
    mechanic: "life-leeching, slow pressure, decay",
    statusEffect: "decay",
    palette: { primary: "#8d5aa8", secondary: "#2b123a", accent: "#d8a2ff", dark: "#050109" },
    defaultCoreMesh: "sphere",
    defaultTravel: ["particle_trail", "swirling_vortex"],
    defaultImpact: ["lingering_cloud", "ground_decal", "flash"],
    defaultShaders: {
      core: "void_swirl",
      trail: "shadow_smoke",
      impact: "necrotic_decay",
      decal: "ground_rune",
      aura: "life_leech_tendril",
    },
    allowedShaders: [
      "void_swirl",
      "shadow_smoke",
      "necrotic_decay",
      "life_leech_tendril",
      "toxic_bubble",
      "acid_sizzle",
      "spore_cloud",
      "thorn_glow",
      "arcane_shimmer",
      "forcefield_ripple",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
  light: {
    id: "light",
    label: "Light",
    primaryVisuals: "gold, brilliant white, halos, radiant motes",
    mechanic: "radiant damage, healing-adjacent support, anti-undead pressure",
    statusEffect: "blind",
    palette: { primary: "#ffe58a", secondary: "#ffffff", accent: "#ffb84a", dark: "#49380f" },
    defaultCoreMesh: "sphere",
    defaultTravel: ["core_glow", "particle_trail"],
    defaultImpact: ["flash", "burst_explosion", "ground_decal"],
    defaultShaders: {
      core: "holy_radiance",
      trail: "sunbeam_core",
      impact: "blinding_flash",
      decal: "halo_ring",
      aura: "halo_ring",
    },
    allowedShaders: [
      "holy_radiance",
      "halo_ring",
      "sunbeam_core",
      "blinding_flash",
      "arcane_shimmer",
      "forcefield_ripple",
      "mana_glass",
      "ward_barrier",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
  meteor_cosmic: {
    id: "meteor_cosmic",
    label: "Meteor / Cosmic",
    primaryVisuals: "deep red, obsidian, star-field, gravity rings",
    mechanic: "massive delayed area impact",
    statusEffect: "crush",
    palette: { primary: "#c73522", secondary: "#160b24", accent: "#ffcf82", dark: "#02030a" },
    defaultCoreMesh: "boulder",
    defaultTravel: ["particle_trail", "core_glow"],
    defaultImpact: ["burst_explosion", "flash", "ground_decal", "lingering_cloud"],
    defaultShaders: {
      core: "meteor_ember",
      trail: "starfield_core",
      impact: "cosmic_impact_ring",
      decal: "gravity_lens",
      aura: "starfield_core",
    },
    allowedShaders: [
      "starfield_core",
      "gravity_lens",
      "meteor_ember",
      "cosmic_impact_ring",
      "flame_core",
      "ember_trail",
      "blast_flash",
      "shockwave_ring",
      "smoke_plume",
      "soft_glow",
      "additive_sprite",
      "ground_rune",
      "dissolve_fade",
    ],
  },
};

export const getAlignment = (id: SpellAlignmentId): AlignmentDefinition => alignmentCatalog[id];
